repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: python
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
        additional_dependencies: [jupyter]
        # - id: ruff
        #   name: ruff
        #   entry: ruff check
        #   language: system
        #   types: [file, python]
        # - id: ruff-format
        #   name: ruff-format
        #   entry: ruff format
        #   language: system
        # types: [file, python]
      - id: black
        name: black
        entry: black
        language: system
        types: [file, python]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [file, python]
      - id: nbqa-black
        name: nbqa-black
        description: Run 'black' on a Jupyter Notebook
        entry: nbqa black
        language: python
        require_serial: true
        types: [jupyter]
        additional_dependencies: [black]
      - id: nbqa-isort
        name: nbqa-isort
        description: Run 'isort' on a Jupyter Notebook
        entry: nbqa isort
        language: python
        require_serial: true
        types: [jupyter]
        additional_dependencies: [isort]
