repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--extend-select, I, --fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports, --allow-untyped-decorators]
        additional_dependencies: [pandas-stubs, types-requests]
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest
        language: system
        types: [python]
        stages: [commit]
        args: [--no-header, -vx, --cov-report, term:skip-covered, --cov=atg, atg/tests/]
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: python
        entry: nb-clean clean --remove-empty-cells
        additional_dependencies: [nb-clean]
      - id: nbqa-ruff
        name: nbqa-ruff
        description: Run 'ruff' on a Jupyter Notebook
        entry: nbqa ruff
        language: python
        require_serial: true
        types: [jupyter]
        additional_dependencies: [ruff]
