Archaea.Euryarchaeota.Methanobacteria.Methanobacteriales.Methanobacteriaceae.Methanobrevibacter	0.0			-
Bacteria	3.9999981088335685			-
Bacteria.Acidobacteria	0.22258032249533682			-
Bacteria.Acidobacteria.Acidobacteria_Gp10.Gp10	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp11.Gp11	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp16.Gp16	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp17.Gp17	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp1.Gp1	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp22.Gp22	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp3.Gp3	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp4.Gp4	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp5.Gp5	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp6.Gp6	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp7.Gp7	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp9.Gp9	0.0			-
Bacteria.Acidobacteria.Holophagae	0.0			-
Bacteria.Acidobacteria.Holophagae.Holophagales.Holophagaceae	0.0			-
Bacteria.Acidobacteria.Holophagae.Holophagales.Holophagaceae.Geothrix	0.0			-
Bacteria.Acidobacteria.Holophagae.Holophagales.Holophagaceae.Holophaga	0.0			-
Bacteria.Actinobacteria.Actinobacteria	3.8268679190231376	High_O2	3.530320303251602	4.148228689669985e-09
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales.Acidimicrobiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales.Acidimicrobiaceae.Ferrithrix	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales.Iamiaceae.Iamia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobidae_incertae_sedis.Ilumatobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales	3.8260944704126767	High_O2	3.529922268218563	3.8412518054506664e-09
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae	2.470414505474463	Mid_O2	2.159789777511494	4.095437367771214e-05
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae.Actinobaculum	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae.Actinomyces	2.464331846051626			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae.Arcanobacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae.Mobiluncus	0.5149880205079682			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinomycetaceae.Varibaculum	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinosynnemataceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Actinosynnemataceae.Lentzea	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Beutenbergiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Beutenbergiaceae.Beutenbergia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Beutenbergiaceae.Salana	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Bogoriellaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Bogoriellaceae.Georgenia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Brevibacteriaceae.Brevibacterium	0.31989686657546934			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cellulomonadaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cellulomonadaceae.Actinotalea	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cellulomonadaceae.Cellulomonas	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cellulomonadaceae.Oerskovia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Corynebacteriaceae	3.1994620717832976	High_O2	2.8908458099098344	1.9448520019630706e-06
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Corynebacteriaceae.Corynebacterium	3.1993232894984542	High_O2	2.890743085573155	1.9448520019630706e-06
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Corynebacteriaceae.Turicella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cryptosporangiaceae.Cryptosporangium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermabacteraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermabacteraceae.Brachybacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermabacteraceae.Dermabacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermacoccaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermacoccaceae.Demetria	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermacoccaceae.Dermacoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermacoccaceae.Kytococcus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dermatophilaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dietziaceae.Dietzia	0.7180349381777283			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Geodermatophilaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Geodermatophilaceae.Blastococcus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Geodermatophilaceae.Geodermatophilus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Geodermatophilaceae.Modestobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae	0.20082383347017743			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Arsenicicoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Janibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Knoellia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Lapillicoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Ornithinimicrobium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Phycicoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Terrabacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Terracoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Intrasporangiaceae.Tetrasphaera	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Jonesiaceae.Jonesia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Kineosporiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Kineosporiaceae.Kineococcus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Kineosporiaceae.Kineosporia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Kineosporiaceae.Quadrisphaera	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae	0.5519748656618491			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Agrococcus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Agromyces	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Clavibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Curtobacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Frigoribacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Leifsonia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Leucobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Microbacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Microcella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Mycetocola	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Plantibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Rathayibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Salinibacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Yonghaparkia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Microbacteriaceae.Zimmermannella	0.1437485107107908			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae	2.505549747683096			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Arthrobacter	0.10647315409236592			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Citricoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Kocuria	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Micrococcus	1.4494334943245428			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Nesterenkonia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Renibacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcaceae.Rothia	2.5032943509963927			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcineae_incertae_sedis.Demequina	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Actinocatenispora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Actinoplanes	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Asanoa	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Catellatospora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Catenuloplanes	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Couchioplanes	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Dactylosporangium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Micromonospora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micromonosporaceae.Virgisporangium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Mycobacteriaceae.Mycobacterium	0.9230775570526409			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nakamurellaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nakamurellaceae.Humicoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nakamurellaceae.Nakamurella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae	0.856777769461609			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae.Gordonia	0.6614768644799357			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae.Millisia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae.Nocardia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae.Rhodococcus	0.18117274976325962			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiaceae.Williamsia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Actinopolymorpha	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Aeromicrobium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Jiangella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Kribbella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Marmoricola	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardioidaceae.Nocardioides	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiopsaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiopsaceae.Nocardiopsis	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Nocardiopsaceae.Thermobifida	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Promicromonosporaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Promicromonosporaceae.Cellulosimicrobium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Promicromonosporaceae.Isoptericola	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Promicromonosporaceae.Promicromonospora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae	3.6971553843597422	High_O2	3.407210376406055	9.483488450996154e-10
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Brooklawnia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Friedmanniella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Luteococcus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Microlunatus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Micropruina	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Propionibacterium	3.6970086409073706	High_O2	3.407131547067962	1.0342281992498534e-09
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Propionicicella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Propioniferax	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Propionimicrobium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Propionibacteriaceae.Tessaracoccus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae	0.10204077572823851			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Actinoalloteichus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Actinomycetospora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Amycolatopsis	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Kibdelosporangium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Prauserella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Pseudonocardia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Saccharomonospora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Saccharopolyspora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Thermobispora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Pseudonocardiaceae.Thermocrispum	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Sanguibacteraceae.Sanguibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptomycetaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptomycetaceae.Kitasatospora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptomycetaceae.Streptomyces	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptosporangiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptosporangiaceae.Microbispora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptosporangiaceae.Nonomuraea	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptosporangiaceae.Sphaerisporangium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Streptosporangiaceae.Thermopolyspora	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Thermomonosporaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Thermomonosporaceae.Actinoallomurus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Thermomonosporaceae.Actinomadura	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Tsukamurellaceae.Tsukamurella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Yaniellaceae.Yaniella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae	2.0195464092324014			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Alloscardovia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Bifidobacterium	0.14448797858656875			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Gardnerella	1.9318817215792372			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Parascardovia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales.Bifidobacteriaceae.Scardovia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae	2.1742722202974054			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Asaccharobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Atopobium	2.1184557643289477			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Collinsella	0.18366096781326702			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Cryptobacterium	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Eggerthella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Enterorhabdus	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Gordonibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Olsenella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Paraeggerthella	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales.Coriobacteriaceae.Slackia	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Nitriliruptorales.Nitriliruptoraceae.Nitriliruptor	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Rubrobacterales.Rubrobacteraceae.Rubrobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Conexibacteraceae.Conexibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Patulibacteraceae.Patulibacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Solirubrobacteraceae.Solirubrobacter	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Thermoleophilales.Thermoleophilaceae.Thermoleophilum	0.0			-
Bacteria.Aquificae.Aquificae.Aquificales.Hydrogenothermaceae.Sulfurihydrogenibium	0.0			-
Bacteria.BRC1.BRC1_genera_incertae_sedis	0.0			-
Bacteria.Bacteria_incertae_sedis.Ktedonobacteria.Ktedonobacterales.Ktedonobacteraceae.Ktedonobacter	0.0			-
Bacteria.Bacteroidetes	3.834567543895116	Low_O2	3.510784826822931	7.288825370808415e-07
Bacteria.Bacteroidetes.Bacteroidetes_incertae_sedis.Prolixibacter	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales	3.8336449979816587	Low_O2	3.510641849889515	8.733110661370889e-07
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidaceae.Bacteroides	3.6138620454183115	Low_O2	3.3027043473325346	3.0342939691410514e-07
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidales_incertae_sedis.Phocaeicola	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae	3.03954957424074	Low_O2	2.717656100239346	3.9831342107334656e-06
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Barnesiella	1.6095958524718939			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Butyricimonas	2.0284294851227744			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Dysgonomonas	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Odoribacter	1.6927061342017113			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Paludibacter	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Parabacteroides	2.8574593500206205	Low_O2	2.540489509061933	1.1878222932965181e-07
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Porphyromonas	2.1264550884340587			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Porphyromonadaceae.Tannerella	0.8863790421219302			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae	2.8890152898751356			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Hallella	0.41259306845113636			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Paraprevotella	2.012113435787956			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Prevotella	2.80009989010627			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Prevotellaceae.Xylanibacter	0.0			-
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Rikenellaceae	2.874111984477532	Low_O2	2.5705840034318803	6.002321098620196e-05
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Rikenellaceae.Alistipes	2.8381286594161916	Low_O2	2.540150507388577	7.352227930198622e-05
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Rikenellaceae.Rikenella	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales	2.580045542848719			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Cryomorphaceae	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Cryomorphaceae.Crocinitomix	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Cryomorphaceae.Fluviicola	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae	2.579518597419719			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Capnocytophaga	2.5404441164996627			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Chryseobacterium	0.41249026723690146			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Cloacibacterium	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Elizabethkingia	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Empedobacter	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Epilithonimonas	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Flavobacterium	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Gelidibacter	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Gillisia	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Kaistella	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Myroides	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Planobacterium	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Riemerella	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Salegentibacter	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Salinimicrobium	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Vitellibacter	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Wautersiella	0.0			-
Bacteria.Bacteroidetes.Flavobacteria.Flavobacteriales.Flavobacteriaceae.Zhouia	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales	0.6576753819776787			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae	0.06446498438454096			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Chitinophaga	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Ferruginibacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Filimonas	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Flavisolibacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Lacibacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Niabella	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Niastella	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Parasegetibacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Sediminibacterium	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Segetibacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Chitinophagaceae.Terrimonas	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cyclobacteriaceae	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae	0.20928097725067232			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Adhaeribacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Arcicella	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Dyadobacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Emticicia	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Flexibacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Hymenobacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Larkinella	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Pontibacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Rudanella	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Runella	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Spirosoma	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Cytophagaceae.Sporocytophaga	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Rhodothermaceae	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Rhodothermaceae.Salinibacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Saprospiraceae	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Saprospiraceae.Haliscomenobacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae	0.028438761898255043			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Mucilaginibacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Nubsella	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Olivibacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Pedobacter	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Solitalea	0.0			-
Bacteria.Bacteroidetes.Sphingobacteria.Sphingobacteriales.Sphingobacteriaceae.Sphingobacterium	0.0			-
Bacteria.Chlamydiae.Chlamydiae.Chlamydiales	0.0			-
Bacteria.Chlamydiae.Chlamydiae.Chlamydiales.Parachlamydiaceae	0.0			-
Bacteria.Chloroflexi	0.0			-
Bacteria.Chloroflexi.Anaerolineae.Anaerolineales.Anaerolineaceae	0.0			-
Bacteria.Chloroflexi.Anaerolineae.Anaerolineales.Anaerolineaceae.Levilinea	0.0			-
Bacteria.Chloroflexi.Anaerolineae.Anaerolineales.Anaerolineaceae.Longilinea	0.0			-
Bacteria.Chloroflexi.Caldilineae.Caldilineales.Caldilineaceae.Caldilinea	0.0			-
Bacteria.Chloroflexi.Chloroflexi	0.0			-
Bacteria.Chloroflexi.Chloroflexi.Chloroflexales.Chloroflexaceae.Chloroflexus	0.0			-
Bacteria.Chloroflexi.Chloroflexi.Herpetosiphonales.Herpetosiphonaceae.Herpetosiphon	0.0			-
Bacteria.Chloroflexi.Thermomicrobia	0.0			-
Bacteria.Chloroflexi.Thermomicrobia.Sphaerobacterales.Sphaerobacteraceae.Sphaerobacter	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria	1.294481611799187			-
Bacteria.Cyanobacteria.Cyanobacteria.Chloroplast	1.2729572346263474			-
Bacteria.Cyanobacteria.Cyanobacteria.Chloroplast.Bacillariophyta	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Chloroplast.Bangiophyceae	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Chloroplast.Chlorophyta	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Chloroplast.Streptophyta	1.26494959258131			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_II.GpIIa	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_IV.GpIV	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_IX.GpIX	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_I.GpI	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_VIII.GpVIII	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_V.GpV	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_XIII.GpXIII	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci	0.08433295616798406			-
Bacteria.Deinococcus_Thermus.Deinococci.Deinococcales	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Deinococcales.Deinococcaceae.Deinococcus	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Deinococcales.Trueperaceae.Truepera	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Thermales.Thermaceae	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Thermales.Thermaceae.Meiothermus	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Thermales.Thermaceae.Thermus	0.0			-
Bacteria.Fibrobacteres.Fibrobacteria.Fibrobacterales.Fibrobacteraceae.Fibrobacter	0.0			-
Bacteria.Firmicutes	3.7562492998388417	Mid_O2	3.2501214932830553	0.0002549901313136027
Bacteria.Firmicutes.Bacilli	3.6630052695908866	Mid_O2	3.3594394733903505	4.6312921475136566e-07
Bacteria.Firmicutes.Bacilli.Bacillales	3.1166781970178614	High_O2	2.7891264956265895	1.7414301797091047e-08
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae	1.355272512822122			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Anoxybacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Bacillus	0.7315672698656829			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Exiguobacterium	1.1496175320172146			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Geobacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Halobacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Lysinibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Oceanobacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Salirhabdus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Salsuginibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Tumebacillus	0.14070077887253343			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillaceae.Ureibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillales_incertae_sedis.Rummeliibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Caryophanaceae.Caryophanon	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Listeriaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Listeriaceae.Brochothrix	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Listeriaceae.Listeria	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Ammoniphilus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Aneurinibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Brevibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Cohnella	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Oxalophagus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Paenibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Saccharibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Thermicanus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Paenibacillaceae.Thermobacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Kurthia	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Paenisporosarcina	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Planococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Planomicrobium	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Planococcaceae.Sporosarcina	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Sporolactobacillaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Sporolactobacillaceae.Marinococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Sporolactobacillaceae.Tuberibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae	3.106584981778531	High_O2	2.7810224920345874	1.761560782791117e-08
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Gemella	1.8743399535657037			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Jeotgalicoccus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Macrococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Nosocomiicoccus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Salinicoccus	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Staphylococcaceae.Staphylococcus	3.0999045266395973	High_O2	2.7744346321258573	1.6109712621476881e-09
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Laceyella	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Planifilum	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Shimazuella	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Thermoactinomycetaceae.Thermoactinomyces	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales	3.655505711192261	Mid_O2	3.351732297245065	5.8897479947988996e-08
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae	1.115689459551041			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Abiotrophia	1.0262090358345741			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Aerococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Eremococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Facklamia	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Globicatella	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Aerococcaceae.Ignavigranum	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae	2.3606065358463058			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Alkalibacterium	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Alloiococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Atopococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Atopostipes	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Carnobacterium	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Desemzia	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Dolosigranulum	2.3494652531344116			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Granulicatella	1.895559539611393			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Marinilactibacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Carnobacteriaceae.Trichococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae	0.39333416177889374			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Bavariicoccus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Catellicoccus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Enterococcus	0.2922238781405058			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Pilibacter	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Tetragenococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Enterococcaceae.Vagococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae	3.410470481195971			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae.Lactobacillus	3.4103682860017153			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae.Paralactobacillus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Lactobacillaceae.Pediococcus	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Leuconostocaceae	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Leuconostocaceae.Leuconostoc	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Leuconostocaceae.Weissella	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae	3.2650505066376243			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae.Lactococcus	0.3121851119801352			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae.Lactovum	0.0			-
Bacteria.Firmicutes.Bacilli.Lactobacillales.Streptococcaceae.Streptococcus	3.2649871491315987			-
Bacteria.Firmicutes.Clostridia	3.3963532608320555	Low_O2	3.038334749177787	2.115881682786302e-06
Bacteria.Firmicutes.Clostridia.Clostridiales	3.390938189209155	Low_O2	3.0327936688464083	2.115881682786302e-06
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae	0.7895509322917745			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae.Alkaliphilus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae.Anaerobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae.Clostridium	0.7117238281289068			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae.Oxobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Clostridiaceae.Sarcina	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae	1.0176325589397153			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Anaerofustis	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Eubacterium	1.0103071220842754			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Garciella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Eubacteriaceae.Pseudoramibacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Gracilibacteraceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Gracilibacteraceae.Gracilibacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI	2.2360970785339425			1.6100047886068535e-05
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XII	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIII	0.7344698821726244			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIII.Anaerovorax	0.41307725695059355			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIII.Mogibacterium	0.7251991788760451			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XII.Fusibacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIV	1.643861960437431			7.0167683690487216e-06
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIV.Anaerovirgula	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIV.Blautia	1.6350506499905428			4.311236886963492e-06
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIV.Howardella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XIV.Proteocatella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Anaerococcus	1.8712606976663122			3.6573700523791524e-06
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Anaerosphaera	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Finegoldia	1.3033649488333487			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Gallicola	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Helcococcus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Parvimonas	1.552135623960832			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Peptoniphilus	1.8790096886664684			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Sporanaerobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Tepidimicrobium	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XI.Tissierella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XVIII.Symbiobacterium	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XVII.Thermaerobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae	2.695126290340925	Low_O2	2.4025819506428596	1.8632849821132932e-05
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Acetitomaculum	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Anaerosporobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Anaerostipes	0.5184315765382659			0.0016069110289558396
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Butyrivibrio	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Catonella	1.3730619675796327			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Coprococcus	1.7766525744048332			6.427852030550064e-06
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Dorea	1.2519253564630652			2.3660860949254326e-05
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Hespellia	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Johnsonella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Lachnobacterium	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Marvinbryantia	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Moryella	1.0798062293845565			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Oribacterium	1.734196005738704			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Parasporobacterium	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Pseudobutyrivibrio	0.36906420548885227			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Robinsoniella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Roseburia	2.1907669957700815			8.358698772474532e-06
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Shuttleworthia	0.1711756594861373			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Lachnospiraceae.Syntrophococcus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae	0.1977618585179296			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae.Dehalobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae.Desulfonispora	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae.Pelotomaculum	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae.Peptococcus	0.11067443877514592			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptococcaceae.Sporotomaculum	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae	1.344258691946366			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae.Filifactor	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae.Peptostreptococcus	0.6130541789455187			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Peptostreptococcaceae.Sporacetigenium	1.0342322594634152			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae	3.0923016841002804	Low_O2	2.7663243737033785	2.9130468096204774e-07
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Acetanaerobacterium	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Acetivibrio	0.8643280031012011			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Anaerofilum	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Anaerotruncus	0.69027151172787			1.178631519694314e-05
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Butyricicoccus	0.7909898076877325			7.555993197687942e-05
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Ethanoligenens	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Faecalibacterium	2.720484999287027	Low_O2	2.4393625097829044	5.514502087128153e-07
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Fastidiosipila	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Hydrogenoanaerobacterium	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Lactonifactor	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Oscillibacter	2.332067374180339	Low_O2	2.0170986753721327	2.7778559499919322e-06
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Papillibacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Ruminococcus	2.285775508800445			0.0004263458271268259
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Sporobacter	0.5401331102538504			0.003121783988607698
Bacteria.Firmicutes.Clostridia.Clostridiales.Ruminococcaceae.Subdoligranulum	1.6134388016345338			1.1030238193532856e-05
Bacteria.Firmicutes.Clostridia.Clostridiales.Syntrophomonadaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae	2.9151668354856164			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Acidaminococcus	0.9629581618590501			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Allisonella	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Anaeroglobus	0.29371789611066634			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Anaerosinus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Anaerovibrio	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Centipeda	0.5852104198401034			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Dendrosporobacter	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Dialister	2.3398606225804848			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Megamonas	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Megasphaera	1.6052527884400813			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Mitsuokella	0.3427235694058218			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Pectinatus	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Phascolarctobacterium	2.01055026121438			0.005299912674522779
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Schwartzia	0.7608365179727267			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Selenomonas	1.6995822159722571			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Sporomusa	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Sporotalea	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Succiniclasticum	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Veillonella	2.814232219225164			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Veillonellaceae.Zymophilus	0.0			-
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae	0.0			-
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae.Caldicellulosiruptor	0.0			-
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae.Gelria	0.0			-
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales.Thermoanaerobacteraceae.Thermoanaerobacterium	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae	1.2082691216525447			1.362102362704755e-05
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Allobaculum	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Bulleidia	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Catenibacterium	0.49183000249001824			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Coprobacillus	0.7724753865916107			5.666002862012607e-05
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Erysipelothrix	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Holdemania	0.3011075158860398			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Sharpea	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Solobacterium	0.0			-
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales.Erysipelotrichaceae.Turicibacter	0.0			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales	2.91800924839425			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Fusobacteriaceae	2.601471393757351			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Fusobacteriaceae.Fusobacterium	2.6013325404862395			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Leptotrichiaceae	2.631421577065365			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Leptotrichiaceae.Leptotrichia	2.2029517668370078			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Leptotrichiaceae.Sneathia	2.4049231321030553			-
Bacteria.Fusobacteria.Fusobacteria.Fusobacteriales.Leptotrichiaceae.Streptobacillus	0.0			-
Bacteria.Gemmatimonadetes.Gemmatimonadetes.Gemmatimonadales.Gemmatimonadaceae.Gemmatimonas	0.0			-
Bacteria.Lentisphaerae.Lentisphaeria	1.004304512125951			-
Bacteria.Lentisphaerae.Lentisphaeria.Victivallales.Victivallaceae.Victivallis	1.0024281733360185			-
Bacteria.Nitrospira.Nitrospira.Nitrospirales.Nitrospiraceae	0.0			-
Bacteria.Nitrospira.Nitrospira.Nitrospirales.Nitrospiraceae.Leptospirillum	0.0			-
Bacteria.Nitrospira.Nitrospira.Nitrospirales.Nitrospiraceae.Nitrospira	0.0			-
Bacteria.OD1.OD1_genera_incertae_sedis	0.0			-
Bacteria.OP10.OP10_genera_incertae_sedis	0.0			-
Bacteria.OP11.OP11_genera_incertae_sedis	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae	0.13442945897307176			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Gemmata	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Isosphaera	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Pirellula	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Planctomyces	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Rhodopirellula	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Singulisphaera	0.0			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales.Planctomycetaceae.Zavarzinella	0.0			-
Bacteria.Proteobacteria	2.852294863077121			-
Bacteria.Proteobacteria.Alphaproteobacteria	1.8183757564475447			-
Bacteria.Proteobacteria.Alphaproteobacteria.Alphaproteobacteria_incertae_sedis	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Alphaproteobacteria_incertae_sedis.Geminicoccus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Alphaproteobacteria_incertae_sedis.Novispirillum	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales.Caulobacteraceae	0.4212072888263078			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales.Caulobacteraceae.Asticcacaulis	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales.Caulobacteraceae.Brevundimonas	0.22748748228870413			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales.Caulobacteraceae.Caulobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales.Caulobacteraceae.Phenylobacterium	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales	1.302181858372118			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Aurantimonadaceae.Aurantimonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Beijerinckiaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Beijerinckiaceae.Beijerinckia	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Beijerinckiaceae.Chelatococcus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae	0.2859197964111441			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Afipia	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Agromonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Balneimonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Blastobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Bosea	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Bradyrhizobium	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Nitrobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Bradyrhizobiaceae.Rhodopseudomonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Brucellaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Brucellaceae.Brucella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Brucellaceae.Ochrobactrum	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Brucellaceae.Pseudochrobactrum	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Blastochloris	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Devosia	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Hyphomicrobium	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Maritalea	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Pedomicrobium	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Hyphomicrobiaceae.Rhodoplanes	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylobacteriaceae	0.9202216744946298			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylobacteriaceae.Methylobacterium	0.9111916802361042			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylobacteriaceae.Microvirga	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylocystaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylocystaceae.Albibacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylocystaceae.Methylocystis	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylocystaceae.Methylopila	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Methylocystaceae.Pleomorphomonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Phyllobacteriaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Phyllobacteriaceae.Aminobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Phyllobacteriaceae.Mesorhizobium	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Phyllobacteriaceae.Phyllobacterium	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhizobiaceae	0.8059718849385242			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhizobiaceae.Ensifer	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhizobiaceae.Kaistia	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhizobiaceae.Rhizobium	0.7839923723747144			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhodobiaceae.Parvibaculum	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Xanthobacteraceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Xanthobacteraceae.Ancylobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Xanthobacteraceae.Labrys	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Xanthobacteraceae.Xanthobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae	1.348704529846301			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Amaricoccus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Haematobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Jannaschia	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Loktanella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Pannonibacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Paracoccus	1.2977144715968874			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Rhodobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales.Rhodobacteraceae.Rubellimicrobium	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales	0.718532336515489			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae	0.6290421046721127			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Acetobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Acidisphaera	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Acidocella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Asaia	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Belnapia	0.05071767919937945			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Craurococcus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Gluconacetobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Gluconobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Paracraurococcus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Rhodopila	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Roseomonas	0.1057844073447323			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Acetobacteraceae.Stella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae.Azospirillum	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae.Defluviicoccus	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae.Magnetospirillum	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae.Rhodocista	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodospirillales.Rhodospirillaceae.Skermanella	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales.Anaplasmataceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales.Rickettsiaceae.Rickettsia	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales.SAR11.Pelagibacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales	1.1192657745137262			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Erythrobacteraceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Erythrobacteraceae.Altererythrobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Erythrobacteraceae.Erythrobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Erythrobacteraceae.Porphyrobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae	1.1025019003200054			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Blastomonas	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Novosphingobium	0.5929987774887292			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sandaracinobacter	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sphingobium	0.4610218992673797			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sphingomonas	0.7201967601172153			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sphingopyxis	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Sphingomonadales.Sphingomonadaceae.Sphingosinicella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria	2.5622702137902063			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales	1.998594498269129			0.0020682778778297983
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae	1.952939926707347			3.2838921863550204e-05
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Achromobacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Alcaligenes	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Azohydromonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Bordetella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Castellaniella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Derxia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Oligella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Parasutterella	1.859844188526921			0.0004807035777694964
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Pigmentiphaga	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Alcaligenaceae.Sutterella	1.2255533262059708			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae	0.8044286835375031			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Burkholderia	0.14179409651025832			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Chitinimonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Cupriavidus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Limnobacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Polynucleobacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Ralstonia	0.6264424965146711			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiaceae.Wautersia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis	0.6316276220213976			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Aquabacterium	0.21949133278983243			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Ideonella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Leptothrix	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Methylibium	0.2629625594444348			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Burkholderiales_incertae_sedis.Tepidimonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae	1.4853475027496255			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Acidovorax	0.17824348717354432			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Alicycliphilus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Brachymonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Comamonas	0.2012474421065039			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Curvibacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Delftia	0.2895183852835982			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Diaphorobacter	0.2172770006668801			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Giesbergeria	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Hydrogenophaga	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Lampropedia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Malikia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Ottowia	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Pelomonas	1.2895228663214195			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Polaromonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Pseudorhodoferax	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Ramlibacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Rhodoferax	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Roseateles	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Schlegelella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Simplicispira	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Tepidicella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Comamonadaceae.Variovorax	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae	0.9403466977690504			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Duganella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Herbaspirillum	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Herminiimonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Janthinobacterium	0.18781239151660853			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Massilia	0.523451795667193			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Naxibacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Burkholderiales.Oxalobacteraceae.Oxalobacter	0.48694743158864073			-
Bacteria.Proteobacteria.Betaproteobacteria.Hydrogenophilales.Hydrogenophilaceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Hydrogenophilales.Hydrogenophilaceae.Hydrogenophilus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Hydrogenophilales.Hydrogenophilaceae.Petrobacter	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Hydrogenophilales.Hydrogenophilaceae.Tepidiphilus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Methylophilales.Methylophilaceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Methylophilales.Methylophilaceae.Methylobacillus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Methylophilales.Methylophilaceae.Methylophilus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Methylophilales.Methylophilaceae.Methylotenera	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae	2.4881878584568073			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Alysiella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Aquaspirillum	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Bergeriella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Conchiformibius	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Formivibrio	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Gulbenkiania	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Kingella	1.6812416820666802			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Neisseria	2.298856041662298			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Simonsiella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Stenoxybacter	0.07416533898168626			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Uruburuella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales.Neisseriaceae.Vogesella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Nitrosomonadales.Nitrosomonadaceae	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Nitrosomonadales.Nitrosomonadaceae.Nitrosomonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Nitrosomonadales.Nitrosomonadaceae.Nitrosospira	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae	0.011801801303068625			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Azonexus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Azospira	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Dechloromonas	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Denitratisoma	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Methyloversatilis	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Propionivibrio	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Rhodocyclus	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Shinella	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Thauera	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Uliginosibacterium	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales.Rhodocyclaceae.Zoogloea	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria	0.5823183999947269			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales.Bacteriovoracaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales.Bacteriovoracaceae.Bacteriovorax	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales.Bacteriovoracaceae.Peredibacter	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales.Bdellovibrionaceae.Bdellovibrio	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales.Desulfobacteraceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales.Desulfobulbaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfobacterales.Desulfobulbaceae.Desulfobulbus	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales	0.4006895649877705			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfomicrobiaceae.Desulfomicrobium	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfovibrionaceae	0.30776777811509326			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfovibrionaceae.Desulfovibrio	0.17399004723726993			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfovibrionaceae.Lawsonia	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfuromonadales	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfuromonadales.Desulfuromonadaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfuromonadales.Geobacteraceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfuromonadales.Geobacteraceae.Geobacter	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales	0.10871191011352367			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Cystobacteraceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Cystobacteraceae.Anaeromyxobacter	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Cystobacteraceae.Archangium	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Cystobacteraceae.Cystobacter	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Haliangiaceae.Haliangium	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Kofleriaceae.Kofleria	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Myxococcaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Myxococcaceae.Myxococcus	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Nannocystaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Nannocystaceae.Enhygromyxa	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Nannocystaceae.Nannocystis	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Polyangiaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Polyangiaceae.Byssovorax	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Polyangiaceae.Sorangium	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Syntrophobacterales.Syntrophobacteraceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Syntrophobacterales.Syntrophobacteraceae.Desulforhabdus	0.0			-
Bacteria.Proteobacteria.Epsilonproteobacteria	1.9373386941128818			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales	1.9370513641838942			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Campylobacteraceae	1.9332713726930724			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Campylobacteraceae.Arcobacter	0.0			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Campylobacteraceae.Campylobacter	1.932691009423016			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Helicobacteraceae	0.0			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Helicobacteraceae.Helicobacter	0.0			-
Bacteria.Proteobacteria.Epsilonproteobacteria.Campylobacterales.Helicobacteraceae.Wolinella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria	2.4928169922805905			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Aeromonadaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Aeromonadaceae.Aeromonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Aeromonadaceae.Tolumonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Succinivibrionaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Succinivibrionaceae.Anaerobiospirillum	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Aeromonadales.Succinivibrionaceae.Succinivibrio	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Alteromonadaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Alteromonadaceae.Alishewanella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Alteromonadaceae.Marinobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Pseudoalteromonadaceae.Pseudoalteromonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Psychromonadaceae.Psychromonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Shewanellaceae.Shewanella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Cardiobacteriales.Cardiobacteriaceae	0.9655457607986763			-
Bacteria.Proteobacteria.Gammaproteobacteria.Cardiobacteriales.Cardiobacteriaceae.Cardiobacterium	0.9601236798789671			-
Bacteria.Proteobacteria.Gammaproteobacteria.Cardiobacteriales.Cardiobacteriaceae.Suttonella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Chromatiales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Chromatiales.Chromatiaceae.Rheinheimera	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae	1.6068828127904065			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Arsenophonus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Buttiauxella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Citrobacter	0.5501514018687689			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Cronobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Enterobacter	0.6133754075453385			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Erwinia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Escherichia_Shigella	0.6468256483481817			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Klebsiella	0.8611536910022286			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Kluyvera	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Morganella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Obesumbacterium	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Pantoea	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Pectobacterium	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Photorhabdus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Proteus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Providencia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Rahnella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Raoultella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Salmonella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Serratia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Trabulsiella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales.Enterobacteriaceae.Yersinia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Gammaproteobacteria_incertae_sedis.Solimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Legionellales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Legionellales.Coxiellaceae.Aquicella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Legionellales.Legionellaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Legionellales.Legionellaceae.Legionella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Methylococcales.Methylococcaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Methylococcales.Methylococcaceae.Methylobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Methylococcales.Methylococcaceae.Methylosarcina	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Halomonadaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Halomonadaceae.Halomonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Halomonadaceae.Kushneria	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Oceanospirillaceae.Marinomonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae	2.4708710268035525			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Actinobacillus	0.942228107025541			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Aggregatibacter	0.8517709408186018			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Bibersteinia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Gallibacterium	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Haemophilus	2.0433832859896843			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Lonepinella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Mannheimia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Nicoletella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Pasteurella	0.5649462296450734			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales.Pasteurellaceae.Phocoenobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales	2.1958008137268545			1.0773847018107676e-06
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae	2.1402631477217597			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Acinetobacter	1.907995121320427			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Alkanindiges	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Enhydrobacter	0.6843468868878578			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Moraxella	1.7170197705044008			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Moraxellaceae.Psychrobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae	1.2731596163044798			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae.Azomonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae.Azorhizophilus	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae.Cellvibrio	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pseudomonadales.Pseudomonadaceae.Pseudomonas	1.2549530746899258			-
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales.Francisellaceae.Francisella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales.Thiotrichaceae.Thiothrix	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Vibrionales.Vibrionaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Vibrionales.Vibrionaceae.Photobacterium	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Vibrionales.Vibrionaceae.Vibrio	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales	0.9666819581212553			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Sinobacteraceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Sinobacteraceae.Hydrocarboniphaga	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Sinobacteraceae.Nevskia	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Sinobacteraceae.Steroidobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae	0.9461258686218639			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Aquimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Arenimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Dokdonella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Dyella	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Ignatzschineria	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Luteimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Lysobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Pseudoxanthomonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Rhodanobacter	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Silanimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Stenotrophomonas	0.2588632656293549			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Thermomonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Wohlfahrtiimonas	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Xanthomonadales.Xanthomonadaceae.Xanthomonas	0.6571774284980267			-
Bacteria.SR1.SR1_genera_incertae_sedis	0.07256619197277045			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales	2.0947865912148926			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Brachyspiraceae.Brachyspira	0.0			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Leptospiraceae.Leptospira	0.0			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Spirochaetaceae	2.0935355618829417			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Spirochaetaceae.Treponema	2.0931859807989333			-
Bacteria.Synergistetes.Synergistia.Synergistales.Synergistaceae	0.5135501041748605			-
Bacteria.Synergistetes.Synergistia.Synergistales.Synergistaceae.Cloacibacillus	0.0			-
Bacteria.Synergistetes.Synergistia.Synergistales.Synergistaceae.Jonquetella	0.0			-
Bacteria.Synergistetes.Synergistia.Synergistales.Synergistaceae.Pyramidobacter	0.0			-
Bacteria.Synergistetes.Synergistia.Synergistales.Synergistaceae.Thermovirga	0.0			-
Bacteria.TM7.TM7_genera_incertae_sedis	1.7764892686635416			-
Bacteria.Tenericutes.Mollicutes	1.2388333333028934			-
Bacteria.Tenericutes.Mollicutes.Acholeplasmatales.Acholeplasmataceae.Acholeplasma	0.0			-
Bacteria.Tenericutes.Mollicutes.Anaeroplasmatales.Anaeroplasmataceae	0.0			-
Bacteria.Tenericutes.Mollicutes.Anaeroplasmatales.Anaeroplasmataceae.Anaeroplasma	0.0			-
Bacteria.Tenericutes.Mollicutes.Anaeroplasmatales.Anaeroplasmataceae.Asteroleplasma	0.0			-
Bacteria.Tenericutes.Mollicutes.Mycoplasmatales.Mycoplasmataceae	1.233051933587905			-
Bacteria.Tenericutes.Mollicutes.Mycoplasmatales.Mycoplasmataceae.Mycoplasma	0.5525749179751612			-
Bacteria.Tenericutes.Mollicutes.Mycoplasmatales.Mycoplasmataceae.Ureaplasma	1.1313929536774794			-
Bacteria.Thermotogae.Thermotogae.Thermotogales.Thermotogaceae	0.0			-
Bacteria.Thermotogae.Thermotogae.Thermotogales.Thermotogaceae.Fervidobacterium	0.0			-
Bacteria.Thermotogae.Thermotogae.Thermotogales.Thermotogaceae.Thermotoga	0.0			-
Bacteria.Verrucomicrobia	1.3170965729484625			-
Bacteria.Verrucomicrobia.Opitutae	0.29097442580698635			-
Bacteria.Verrucomicrobia.Opitutae.Opitutales.Opitutaceae.Opitutus	0.0			-
Bacteria.Verrucomicrobia.Opitutae.Puniceicoccales.Puniceicoccaceae	0.27117559473380065			-
Bacteria.Verrucomicrobia.Opitutae.Puniceicoccales.Puniceicoccaceae.Coraliomargarita	0.260925889745443			-
Bacteria.Verrucomicrobia.Spartobacteria	0.0			-
Bacteria.Verrucomicrobia.Spartobacteria.Spartobacteria_genera_incertae_sedis	0.0			-
Bacteria.Verrucomicrobia.Subdivision3.Subdivision3_genera_incertae_sedis	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae	1.2701040694782786			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae.Akkermansia	1.2649974282694463			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae.Haloferula	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae.Luteolibacter	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae.Prosthecobacter	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales.Verrucomicrobiaceae.Verrucomicrobium	0.0			-
Archaea	0.0			-
Archaea.Euryarchaeota	0.0			-
Archaea.Euryarchaeota.Methanobacteria	0.0			-
Archaea.Euryarchaeota.Methanobacteria.Methanobacteriales	0.0			-
Archaea.Euryarchaeota.Methanobacteria.Methanobacteriales.Methanobacteriaceae	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp10	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp11	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp16	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp17	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp1	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp22	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp3	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp4	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp5	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp6	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp7	0.0			-
Bacteria.Acidobacteria.Acidobacteria_Gp9	0.0			-
Bacteria.Acidobacteria.Holophagae.Holophagales	0.0			-
Bacteria.Actinobacteria	4.426613803166968	High_O2	4.130395910335447	4.148228689669985e-09
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobiales.Iamiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Acidimicrobidae_incertae_sedis	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Brevibacteriaceae	0.31989686657546934			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Cryptosporangiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Dietziaceae	0.7180349381777283			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Jonesiaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Micrococcineae_incertae_sedis	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Mycobacteriaceae	0.9230775570526409			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Sanguibacteraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Tsukamurellaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Actinomycetales.Yaniellaceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Bifidobacteriales	2.2811536370276766			-
Bacteria.Actinobacteria.Actinobacteria.Coriobacteriales	2.449724445937834			-
Bacteria.Actinobacteria.Actinobacteria.Nitriliruptorales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Nitriliruptorales.Nitriliruptoraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Rubrobacterales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Rubrobacterales.Rubrobacteraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Conexibacteraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Patulibacteraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Solirubrobacterales.Solirubrobacteraceae	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Thermoleophilales	0.0			-
Bacteria.Actinobacteria.Actinobacteria.Thermoleophilales.Thermoleophilaceae	0.0			-
Bacteria.Aquificae	0.0			-
Bacteria.Aquificae.Aquificae	0.0			-
Bacteria.Aquificae.Aquificae.Aquificales	0.0			-
Bacteria.Aquificae.Aquificae.Aquificales.Hydrogenothermaceae	0.0			-
Bacteria.BRC1	0.0			-
Bacteria.Bacteria_incertae_sedis	0.0			-
Bacteria.Bacteria_incertae_sedis.Ktedonobacteria	0.0			-
Bacteria.Bacteria_incertae_sedis.Ktedonobacteria.Ktedonobacterales	0.0			-
Bacteria.Bacteria_incertae_sedis.Ktedonobacteria.Ktedonobacterales.Ktedonobacteraceae	0.0			-
Bacteria.Bacteroidetes.Bacteroidetes_incertae_sedis	0.0			-
Bacteria.Bacteroidetes.Bacteroidia	4.201029353142378	Low_O2	3.8823332161443416	6.573396801716949e-07
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidaceae	3.6138620454183115	Low_O2	3.3027043473325346	3.0342939691410514e-07
Bacteria.Bacteroidetes.Bacteroidia.Bacteroidales.Bacteroidales_incertae_sedis	0.0			-
Bacteria.Bacteroidetes.Flavobacteria	3.044813303122666			-
Bacteria.Bacteroidetes.Sphingobacteria	1.0858853769618146			-
Bacteria.Chlamydiae	0.0			-
Bacteria.Chlamydiae.Chlamydiae	0.0			-
Bacteria.Chloroflexi.Anaerolineae	0.0			-
Bacteria.Chloroflexi.Anaerolineae.Anaerolineales	0.0			-
Bacteria.Chloroflexi.Caldilineae	0.0			-
Bacteria.Chloroflexi.Caldilineae.Caldilineales	0.0			-
Bacteria.Chloroflexi.Caldilineae.Caldilineales.Caldilineaceae	0.0			-
Bacteria.Chloroflexi.Chloroflexi.Chloroflexales	0.0			-
Bacteria.Chloroflexi.Chloroflexi.Chloroflexales.Chloroflexaceae	0.0			-
Bacteria.Chloroflexi.Chloroflexi.Herpetosiphonales	0.0			-
Bacteria.Chloroflexi.Chloroflexi.Herpetosiphonales.Herpetosiphonaceae	0.0			-
Bacteria.Chloroflexi.Thermomicrobia.Sphaerobacterales	0.0			-
Bacteria.Chloroflexi.Thermomicrobia.Sphaerobacterales.Sphaerobacteraceae	0.0			-
Bacteria.Cyanobacteria	1.7627392843444776			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_II	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_IV	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_IX	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_I	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_VIII	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_V	0.0			-
Bacteria.Cyanobacteria.Cyanobacteria.Family_XIII	0.0			-
Bacteria.Deinococcus_Thermus	0.5296962003306195			-
Bacteria.Deinococcus_Thermus.Deinococci.Deinococcales.Deinococcaceae	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Deinococcales.Trueperaceae	0.0			-
Bacteria.Deinococcus_Thermus.Deinococci.Thermales	0.0			-
Bacteria.Fibrobacteres	0.0			-
Bacteria.Fibrobacteres.Fibrobacteria	0.0			-
Bacteria.Fibrobacteres.Fibrobacteria.Fibrobacterales	0.0			-
Bacteria.Fibrobacteres.Fibrobacteria.Fibrobacterales.Fibrobacteraceae	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Bacillales_incertae_sedis	0.0			-
Bacteria.Firmicutes.Bacilli.Bacillales.Caryophanaceae	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XVIII	0.0			-
Bacteria.Firmicutes.Clostridia.Clostridiales.Incertae_Sedis_XVII	0.0			-
Bacteria.Firmicutes.Clostridia.Thermoanaerobacterales	0.0			-
Bacteria.Firmicutes.Erysipelotrichi	1.451151610057668			1.9696591941788733e-05
Bacteria.Firmicutes.Erysipelotrichi.Erysipelotrichales	1.451151610057668			1.9696591941788733e-05
Bacteria.Fusobacteria	3.3924325781127855			-
Bacteria.Fusobacteria.Fusobacteria	3.3924325781127855			-
Bacteria.Gemmatimonadetes	0.0			-
Bacteria.Gemmatimonadetes.Gemmatimonadetes	0.0			-
Bacteria.Gemmatimonadetes.Gemmatimonadetes.Gemmatimonadales	0.0			-
Bacteria.Gemmatimonadetes.Gemmatimonadetes.Gemmatimonadales.Gemmatimonadaceae	0.0			-
Bacteria.Lentisphaerae	1.3043973517179135			-
Bacteria.Lentisphaerae.Lentisphaeria.Victivallales	1.0024281733360185			-
Bacteria.Lentisphaerae.Lentisphaeria.Victivallales.Victivallaceae	1.0024281733360185			-
Bacteria.Nitrospira	0.0			-
Bacteria.Nitrospira.Nitrospira	0.0			-
Bacteria.Nitrospira.Nitrospira.Nitrospirales	0.0			-
Bacteria.OD1	0.0			-
Bacteria.OP10	0.0			-
Bacteria.OP11	0.0			-
Bacteria.Planctomycetes	0.40349045444877224			-
Bacteria.Planctomycetes.Planctomycetacia	0.40349045444877224			-
Bacteria.Planctomycetes.Planctomycetacia.Planctomycetales	0.40349045444877224			-
Bacteria.Proteobacteria.Alphaproteobacteria.Caulobacterales	0.712012438058802			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Aurantimonadaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhizobiales.Rhodobiaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rhodobacterales	1.6457772674644444			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales.Rickettsiaceae	0.0			-
Bacteria.Proteobacteria.Alphaproteobacteria.Rickettsiales.SAR11	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Hydrogenophilales	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Methylophilales	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Neisseriales	2.720262423622989			-
Bacteria.Proteobacteria.Betaproteobacteria.Nitrosomonadales	0.0			-
Bacteria.Proteobacteria.Betaproteobacteria.Rhodocyclales	0.2943484990811764			-
Bacteria.Proteobacteria.Deltaproteobacteria.Bdellovibrionales.Bdellovibrionaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Desulfovibrionales.Desulfomicrobiaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Haliangiaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Myxococcales.Kofleriaceae	0.0			-
Bacteria.Proteobacteria.Deltaproteobacteria.Syntrophobacterales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Pseudoalteromonadaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Psychromonadaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Alteromonadales.Shewanellaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Cardiobacteriales	1.265226439857118			-
Bacteria.Proteobacteria.Gammaproteobacteria.Chromatiales.Chromatiaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Enterobacteriales	1.8068683417127755			-
Bacteria.Proteobacteria.Gammaproteobacteria.Gammaproteobacteria_incertae_sedis	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Legionellales.Coxiellaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Methylococcales	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Oceanospirillales.Oceanospirillaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Pasteurellales	2.6295092336046935			-
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales.Francisellaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Thiotrichales.Thiotrichaceae	0.0			-
Bacteria.Proteobacteria.Gammaproteobacteria.Vibrionales	0.0			-
Bacteria.SR1	0.07256619197277045			-
Bacteria.Spirochaetes	2.5710914833306258			-
Bacteria.Spirochaetes.Spirochaetes	2.5710914833306258			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Brachyspiraceae	0.0			-
Bacteria.Spirochaetes.Spirochaetes.Spirochaetales.Leptospiraceae	0.0			-
Bacteria.Synergistetes	0.5430360748828467			-
Bacteria.Synergistetes.Synergistia	0.5430360748828467			-
Bacteria.Synergistetes.Synergistia.Synergistales	0.5430360748828467			-
Bacteria.TM7	1.7764892686635416			-
Bacteria.Tenericutes	1.7145165086103646			-
Bacteria.Tenericutes.Mollicutes.Acholeplasmatales	0.0			-
Bacteria.Tenericutes.Mollicutes.Acholeplasmatales.Acholeplasmataceae	0.0			-
Bacteria.Tenericutes.Mollicutes.Anaeroplasmatales	0.0			-
Bacteria.Tenericutes.Mollicutes.Mycoplasmatales	1.5340819274911113			-
Bacteria.Thermotogae	0.0			-
Bacteria.Thermotogae.Thermotogae	0.0			-
Bacteria.Thermotogae.Thermotogae.Thermotogales	0.0			-
Bacteria.Verrucomicrobia.Opitutae.Opitutales	0.0			-
Bacteria.Verrucomicrobia.Opitutae.Opitutales.Opitutaceae	0.0			-
Bacteria.Verrucomicrobia.Opitutae.Puniceicoccales	0.5671109748795022			-
Bacteria.Verrucomicrobia.Subdivision3	0.0			-
Bacteria.Verrucomicrobia.Verrucomicrobiae	1.570626142457333			-
Bacteria.Verrucomicrobia.Verrucomicrobiae.Verrucomicrobiales	1.570626142457333			-
